// C:\Users\alwynn\Desktop\Todo-App\REACT-CRUD-WITH-V1-CDM-API-INTEGRATION\REACT-WEB\src\common\models\cdm.ts

// Represents the TempTestRecordModel from the backend
export interface Record {
  Id: number | null; // Backend uses int?, so number | null
  Name: string;      // Backend uses Name instead of Title
  Description: string | null;
  // Removed Version, CreatedAt, CreatedBy, LastUpdatedAt, LastUpdatedBy,
  // IsGlobal, IsDefault, IsDeprecated, DeprecationDate as they are not in TempTestRecordModel
}

// DTO for creating a new record (Id is auto-generated by backend)
export interface CreateRecordDto {
  Name: string; // Backend uses Name
  Description: string | null;
  // Removed IsGlobal, IsDefault as they are not in TempTestRecordModel
}

// DTO for updating an existing record
export interface UpdateRecordDto {
  Id: number;        // Id is required for updating
  Name?: string;     // Backend uses Name
  Description?: string | null;
  // Removed IsGlobal, IsDefault, IsDeprecated, DeprecationDate
}

// Backend's PagedResult structure (assuming a generic PagedResult)
export interface PagedResult<T> {
  Items: T[];
  PageNumber: number;
  PageSize: number;
  TotalCount: number;
  TotalPages: number;
  HasPreviousPage: boolean;
  HasNextPage: boolean;
}
